<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.3 (Python 3.13.2 on win32)" generated="2025-06-26T11:01:40.370901" rpa="false" schemaversion="5">
<suite id="s1" name="testDemo5" source="C:\Users\varun\PycharmProjects\RobotFramework\tests\testDemo5.robot">
<test id="s1-t1" name="Login with username ${username} and password ${password}" line="15">
<status status="FAIL" start="2025-06-26T11:01:40.945110" elapsed="0.001196">Test cannot be empty.</status>
</test>
<doc>To Validate the Login Page</doc>
<status status="FAIL" start="2025-06-26T11:01:40.374250" elapsed="0.573428"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="testDemo5" id="s1" pass="0" fail="1" skip="0">testDemo5</stat>
</suite>
</statistics>
<errors>
<msg time="2025-06-26T11:01:40.938030" level="ERROR">[ DataDriver ] Error in robot file:
  File "C:\Users\varun\PycharmProjects\RobotFramework\tests\testDemo5.robot", line 0</msg>
<msg time="2025-06-26T11:01:40.938416" level="ERROR">In source file:
  File "data.csv", line 0</msg>
<msg time="2025-06-26T11:01:40.942582" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\varun\PycharmProjects\RobotFramework\tests\data.csv but file does not exist.</msg>
</errors>
</robot>
